[[language]]
name = "hcl"
auto-format = true

[[language]]
name = "markdown"
auto-format = true
file-types = ["md"]
formatter = { command = "prettier", args = [
    "--parser",
    "markdown",
    "--print-width",
    "100",
    "--prose-wrap",
    "always",
] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt", args = [] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "uvx", args = ["ruff", "format", "-"] }

[[language]]
name = "sql"
auto-format = false
file-types = ["sql"]
formatter = { command = "sleek", args = [
    "--indent-spaces",
    "2",
    "--uppercase",
] }

[[language]]
name = "yaml"
auto-format = true
file-types = ["yml", "yaml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
